/*
Copyright 2017 Patrick McGurk
This file is part of ChromatVis.

ChromatVis is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

ChromatVis is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with ChromatVis.  If not, see <http://www.gnu.org/licenses/>.
*/

/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:482438:
  openTrace();
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton1:482438:

/*public void resizeButton_click1(GImageButton source, GEvent event){
  print(event.toString() + "\n");
  if (event.toString() == "CLICKED") {
    //((TraceWinData)source.getPApplet().data).resizePanel.setVisible(true);
    print("This is the resize button");
  }
}*/

// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  imgButton1 = new GImageButton(this, 4, 4, new String[] { "open-archive.png", "open-archive.png", "open-archive.png" } , "allblack.png");
  imgButton1.addEventHandler(this, "imgButton1_click1");
  buttonLabel = new GLabel(this, 38, 12, 185, 20);
  buttonLabel.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  buttonLabel.setText("Select chromatogram files to align");
  buttonLabel.setOpaque(true);
}

// Variable declarations 
// autogenerated do not edit
GImageButton imgButton1;
GLabel buttonLabel;